---
title: "First Knit"
author: "Rachel Polack"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I went to high school at Quartz Hill High School, I graduated in 1999. For me, English has always been much easier than math. The subject I did best in was nutrition and cooking.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
My computer runs on Windows 10. I would have to rate myself as a 5, because although I am not a complete dummy, I do not know much about computers, which is why I always have my daughter help me. The internet is ok where I live, not perfect but it works more than 70 percent of the time.   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
My friends sometimes call me Red because usually my hair is dyed red and we already have a Rachel in the group, but I would rather be called by my name, Rachel. I have tried to go by my nicknames in class, but it never worked out because I would forget to answer the teacher until they called me by my real name.   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
My goal is to study Psychology and recieve my Masters degree and open my own practice. I want to work with children and adolescents who are in the foster system or who have been adopted.   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
 I went to Israel for my Aunt Sharon's wedding when I was a very young child. I made the mistake of splashing in the Dead Sea, which is the saltiest body of water in the world. I got water in my eyes and I can still remember the pain and I was unable to see for an hour. I also have been to Mexico, my grandparents owned a beach house there when I was a child. I plan to travel around the world, I want to go to Japan, Ireland, Scotland, Wales, Spain, Turkey, and India, just to name a few places. I have never been in the military, I am on many different medications due to my poor health, so I would never get drafted.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
 I took Statistics at another college, but because I had to retake it because my credits were not transferable. I have never used the R program so I decided to enroll in this class instead. I had no idea about the requirements, all I knew was that I needed to learn about the programs that the statistics classes use. I would like to get a B in this class, so I can increase my G.P.A. and it looks good to other colleges if I do well in math. My daughter, Annabelle, is in this class with me, so she is willing to help me understand the assignments so I will do well on them.   
 






  




